# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: 3-Tier-python-postgres-app

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
  Code_Analysis-Security_Check:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install flask8
      run: |
        python -m pip install --upgrade pip
        pip install flake8 
        
    - uses: actions/checkout@v4
    - name: Lint with flake8 #Code anaysis
      run: flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Trivy Install
      run: |
       sudo apt-get install -y wget gnupg
       wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
       echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
       sudo apt-get update -y
       sudo apt-get install trivy -y

    - name: Trivy FS scan
      run: trivy fs --format table -o fs-report.json .
      
    - name: Gitleaks Installation
      run: sudo apt install gitleaks -y
      
    - name: Gitleaks code scan
      run: gitleaks detect source . -r gitleaks-report.json -f json
      
 
